### PR TITLE
remove secret as we don't need it for now

### PR DESCRIPTION
**Pull request by cornelius-keller**
removing cluser service secret as we don't need it for now

### CODE REVIEW

**Comment by MarcelMue** [comment]
I think the reference to the secret inside the deployment should also be removed.

**Review by stone-z — CHANGES_REQUESTED** [review]
I think the test chart values has a typo in the name. Probably supposed to be test-values.yaml? Otherwise good to go

**Comment by cornelius-keller** [comment]
Hi Zach, the file should not even be there. Removed it from the commit and
force pushed.

**Review by stone-z — APPROVED** [review]

**Comment by tfussell** [comment]
Towards https://github.com/giantswarm/giantswarm/issues/6893

**Review by MarcelMue — APPROVED** [review]

**Pull request merged**
